import 'package:cloud_firestore/cloud_firestore.dart';

/// Mirrors SellerPaymentRemoteDS, keyed by buyerId instead of sellerId.
/// Backs the buyer online-payment flow — see razorpayWebhook's
/// buyer_order_payments branch (functions/index.js) for how a captured
/// payment turns into the real orders/{orderId} doc.
class BuyerOrderPaymentRemoteDS {
  final FirebaseFirestore _firestore = FirebaseFirestore.instance;

  /// STEP 1: Create payment record BEFORE opening Razorpay. [orderId] is
  /// pre-generated by the caller so the webhook can write the real order
  /// doc to a known id and the client can watch for it to appear.
  Future<String> createPendingPayment({
    required String buyerId,
    required String sellerId,
    required String shopId,
    required String societyId,
    required String flatNumber,
    required String societyName,
    required String shopName,
    required String shopPhone,
    required List<Map<String, dynamic>> items,
    required double totalAmount,
    required String orderId,
  }) async {
    final docRef = _firestore.collection('buyer_order_payments').doc();

    await docRef.set({
      'buyerId': buyerId,
      'sellerId': sellerId,
      'shopId': shopId,
      'societyId': societyId,
      'flatNumber': flatNumber,
      'societyName': societyName,
      'shopName': shopName,
      'shopPhone': shopPhone,
      'items': items,
      'totalAmount': totalAmount,
      'orderId': orderId,
      'gateway': 'razorpay',
      'status': 'initiated', // initiated | order_created | completed | failed
      'createdAt': FieldValue.serverTimestamp(),
    });

    return docRef.id;
  }

  /// Mark payment failure (cancelled/declined at the Razorpay checkout).
  Future<void> markPaymentFailed({
    required String paymentDocId,
    required String failureReason,
  }) async {
    await _firestore
        .collection('buyer_order_payments')
        .doc(paymentDocId)
        .update({
      'status': 'failed',
      'failureReason': failureReason,
      'failedAt': FieldValue.serverTimestamp(),
    });
  }
}
